export const defaultSettings = {
  storeName: '806 & CO.',
  tagline: 'Your one stop shop for all things creative.',
  marqueeText: 'SPRAY TANS · BIRTHDAY SIGNS · CUSTOM GLOW · AMARILLO ·',
  homeHeroPhotoUrl: '',
  homeHeroPhotoUrls: [],
  heroSlideshowInterval: 5,
  contactEmail: 'hello@806andcompany.com',
  instagramUrl: '',
  instagramEmbedUrl: '',
  facebookUrl: '',
  facebookEmbedUrl: '',
  ownerEmail: 'hello@806andcompany.com',
  paypal: {
    enabled: false,
    clientId: '',
    paymentLink: '',
    mode: 'sandbox',
  },
  venmo: {
    enabled: false,
    handle: '',
  },
  cashapp: {
    enabled: false,
    cashtag: '',
  },
  siteAnimation: {
    enabled: false,
    emoji: '✨',
    direction: 'up',
    loop: 'infinite',
    duration: 30,
    activeMonth: 0,
    quantity: 12,
    speed: 1,
  },
  categories: ['Spray Tans', 'Birthday Signs', 'Kirby', 'Self Tanners'],
  shipping: {
    defaultShippingRate: 8,
    freeShippingMinimum: 75,
    localDeliveryFee: 12,
    pickupFee: 0,
    mileageRate: 0.7,
    useMileageDelivery: false,
    deliveryOrigin: {
      street: '',
      city: 'Amarillo',
      state: 'TX',
      zip: '',
    },
  },
  about: {
    heroEyebrow: 'established 2022',
    heroTitle: 'Confidence.\nWith a Healthy Glow.',
    storyHeading: "Hi, I'm Laney —\nthe heart behind\n806 & CO.",
    storyP1: "Founded with the mission to give clients a boost of confidence with a healthy glow, 806 & CO. (formerly Tanning Amarillo) is known for custom spray tans, superior customer service, and fun, friendly technicians.",
    storyP2: "Once the preferred salon for airbrush tans among Texas Tech students in Amarillo, we've relocated to Amarillo — bringing the same flawless glow and creative energy to the Panhandle.",
    storyP3: "In addition to airbrush tans, 806 & CO. offers custom self tanners and birthday signs. The possibilities are endless. Owned and operated by Laney Whitefield, we're here to give every client a flawless tan and a little extra confidence.",
    pullQuote: '\u201cNot only does Laney have great service, but she gave me a glowing spray tan for game day that I loved!\u201d',
    craftHeading: 'Glow.\nCreate.\nCelebrate.',
    ctaText: 'Ready for your custom glow?',
    craftCards: [
      { icon: '☀️', image: '', title: 'Spray Tans', description: 'Custom airbrush tans tailored to your skin tone — including wedding expertise, group discounts, and mobile options.' },
      { icon: '🎉', image: '', title: 'Birthday Signs', description: 'Custom birthday signs made to celebrate your day — bold, personal, and photo-ready.' },
      { icon: '✨', image: '', title: 'Kirby & More', description: 'Creative extras and custom self-tanners so you can keep that sun-kissed look on the go.' },
    ],
  },
}

export const mockProducts = [
  {
    id: 'sample-1',
    name: 'Custom Airbrush Spray Tan',
    description: 'A personalized airbrush spray tan customized to your skin tone for a natural, flawless glow.',
    pricingMode: 'standard',
    price: 45,
    category: 'Spray Tans',
    images: ['https://images.unsplash.com/photo-1515377905703-c43d4a4ab1d5?auto=format&fit=crop&w=900&q=80'],
    video: '',
    inStock: true,
    quantity: 20,
    featured: true,
    visible: true,
    localOnly: true,
    shippable: false,
    createdAt: Date.now(),
    booking: {
      enabled: true,
      displayName: 'Custom Airbrush Spray Tan',
      slotDurationMinutes: 30,
      bufferMinutes: 0,
      bookingCloseHours: 24,
      advanceBookingDays: 60,
      timezone: 'America/Chicago',
      infoMessage: 'Mobile spray tans — we come to you in the Amarillo area.',
      depositAmount: 0,
      weeklyHours: {
        sunday: [],
        monday: [{ start: '16:00', end: '20:00' }],
        tuesday: [{ start: '16:00', end: '20:00' }],
        wednesday: [{ start: '16:00', end: '20:00' }],
        thursday: [{ start: '16:00', end: '20:00' }],
        friday: [{ start: '16:00', end: '20:00' }],
        saturday: [{ start: '10:00', end: '14:00' }],
      },
      blockedDates: [],
    },
  },
  {
    id: 'sample-2',
    name: 'Custom Birthday Sign',
    description: 'A custom birthday sign designed for your celebration — perfect for photos and parties.',
    pricingMode: 'standard',
    price: 35,
    category: 'Birthday Signs',
    images: ['https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=900&q=80'],
    video: '',
    inStock: true,
    quantity: 10,
    featured: true,
    visible: true,
    createdAt: Date.now(),
  },
  {
    id: 'sample-3',
    name: 'Custom Self Tanner',
    description: 'Premium custom tan in a bottle — maintain your glow at home or on the go.',
    pricingMode: 'standard',
    price: 28,
    category: 'Self Tanners',
    images: ['https://images.unsplash.com/photo-1570172619604-71d7826afdab?auto=format&fit=crop&w=900&q=80'],
    video: '',
    inStock: true,
    quantity: 15,
    featured: false,
    visible: true,
    createdAt: Date.now(),
  },
]

export const mockGalleryItems = [
  {
    id: 'gallery-1',
    title: 'Wedding Day Glow',
    type: 'Spray Tan',
    description: 'Custom bridal airbrush tan for a natural, camera-ready glow.',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    pinned: true,
    createdAt: Date.now(),
  },
  {
    id: 'gallery-2',
    title: 'Game Day Tan',
    type: 'Spray Tan',
    description: 'Flawless custom spray tan ready for game day photos.',
    image: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80',
    pinned: false,
    createdAt: Date.now() - 1,
  },
  {
    id: 'gallery-3',
    title: 'Custom Birthday Sign',
    type: 'Birthday Sign',
    description: 'Bold, personalized birthday sign for celebrations and photo moments.',
    image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=1200&q=80',
    pinned: false,
    createdAt: Date.now() - 2,
  },
]
